version: 0.0  # CodeDeploy의 버전, 프로젝트의 버전이 아님, 0.0이외 다른 버전을 사용하면 오류발생
os: linux
files:
  - source: /  # CodeDeploy에서 전달해준 파일 중 destination으로 이동시킬 대상 지정, / root경로를 지정하면 전체파일을 이야기함
    destination: /home/ec2-user/app/step2/zip/  # source에서 지정된 파일을 받을 위치, 이후 Jar를 실행하는 등은 destination으로 옮긴파일들로 진행
    overwrite: yes  # 기존에 파일들이 있으면 덮어쓸지를 결정(yes)
