spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://aws-mykim-db.cnabvg8k9c9s.ap-northeast-2.rds.amazonaws.com:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: mykim
    password: kmy5708!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none