server:
  port: 8080

debug: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

#awsParameterStorePropertySource:
#  enabled: true

spring:
  config:
    activate:
      on-profile: prod

  # jpa
  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        metadata_builder_contributor: io.mykim.projectboard.global.config.mysql.CustomMysqlDialect

  #DB Connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${/project-board/cloud-parameter-store_prod/DB_URL}
    username: ${/project-board/cloud-parameter-store_prod/DB_USERNAME}
    password: ${/project-board/cloud-parameter-store_prod/DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          #google
          google:
            client-id: ${/project-board/cloud-parameter-store_prod/OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${/project-board/cloud-parameter-store_prod/OAUTH2_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

          #naver
          naver:
            client-id: ${/project-board/cloud-parameter-store_prod/OAUTH2_NAVER_CLIENT_ID}
            client-secret: ${/project-board/cloud-parameter-store_prod/OAUTH2_NAVER_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email
              - nickname

          # kakao
          kakao:
            client-id: ${/project-board/cloud-parameter-store_prod/OAUTH2_KAKAO_CLIENT_ID}
            client-secret: ${/project-board/cloud-parameter-store_prod/OAUTH2_KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - account_email
              - profile_nickname

        provider:
          # naver
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          # kakao
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  sql.init.mode: never

