spring:
  config:
    activate:
      on-profile: dev

  # DB Connection
  datasource:
    url: ENC(CS92Tt3CVi9b/jl5jHytt/L5h0UeJNZwxREzIXihxTNfIol0vBv5henwHAfXD2JtKO4MwV2mjV3pwenkwQ5kfVNyHdgsiz90KTauy8uNhwHLocbbhOZsqF5j4ZGL/Np6rxrXs8YaP5pYOyP+a1yZgs9Qbskj3nv2+H9T6sc+90w=)
    username: ENC(cgCoNlPFZqMYcbCfur4Hug==)
    password: ENC(wVSpofhv4sU1WUFKiVQi5nID+CCoUn1I)
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 관련
  jpa:
    defer-datasource-initialization: true
      #초기 테스트 용 데이터 입력을 위한 data.sql 작동 활성화

    hibernate:
      ddl-auto: create
      # ddl-auto: 'option'
        # none : 아무것도 하지 않는다.
        # create : 기존의 테이블이 있다면, 지우고 새로 만듬.
        # create-drop : 테이블을 새로 만들고, 앱이 꺼지기 전에 지운다.
        # update : Entity에서 추가된 필드를 테이블에 반영한다.(테이블 수정)
        # validate : Entity와 테이블의 정합성이 맞는지 검증한다.(안맞으면 오류를 발생 : Application 종료)

    show-sql: true
      # SQL query 출력

  sql.init.mode: always
    #app실행 시 data.sql 실행