debug: false
  # logback의 debug 모드를 비활성화

management.endpoints.web.exposure.include: "*"
  # spring actuator의 엔드포인트 중 감춰져있는 것을 모두 활성화

logging:
  level:
    io.mykim.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.SQL: debug
      # Logger를 통해 하이버네이트 실행 SQL을 남김

server:
  port: 8080

spring:
  profiles:
    active: local

  #DB Connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(7pDf1vwRUGg76FyU91mbMhnBvoMvBYD/doKsfB1o6ciep0tzgcOkaoxz7wMzDiM2FCkilm4PdnPT/OUYlEUUBIAzGPTpgcdU+I9/aihyPQbeWl1mGtGLvkdtB7RokwZgGgaWQk+nEndnlSPWpp7z4O6wNHzj2a9R1+qRcOEOKpc=)
    username: ENC(QgP9QWvVGt0A/mPmAZtBGQ==)
    password: ENC(ypHIP7vlbMV3BO49swIlwsUxL4e2xyUp)

  # JPA 관련
  jpa:
    defer-datasource-initialization: true
      #초기 테스트 용 데이터 입력을 위한 data.sql 작동 활성화

    open-in-view: false
      # OSIV 설정 : Open Session In View(하이버네이트), Open EntityManager In View(JPA)
        # default : true
        # [true]
        # - 트랜잭션 시작처럼 최초 데이터베이스 커넥션 시작 시점부터 API 응답이 끝날 때 까지 영속성 컨텍스트와 데이터베이스 커넥션을 유지
        # - 그렇기때문에 View Template이나 API 컨트롤러에서 지연 로딩이 가능
        # - 지연 로딩은 영속성 컨텍스트가 살아있어야 가능하고, 영속성 컨텍스트는 기본적으로 데이터베이스 커넥션을 유지한다. → 이것 자체가 큰 장점이다.
        # - 이 전략은 너무 오랜시간동안 데이터베이스 커넥션 리소스를 사용하기 때문에, 실시간 트래픽이 중요한 애플리케이션에서는 커넥션이 모자랄 수 있다. → 이것은 결국 장애로 이어진다
        # - 컨트롤러에서 외부 API를 호출하면 외부 API 대기 시간 만큼 커넥션 리소스를 반환하지 못하고, 유지해야 한다.
        # [false]
        # - 트랜잭션을 종료할 때 영속성 컨텍스트를 닫고, 데이터베이스 커넥션도 반환
        # - 모든 지연로딩을 트랜잭션 안에서 처리
        # - 지연로딩 코드를 트랜잭션 안으로 넣어야 하는 단점
        # - 트랜잭션이 끝나기 전에 지연 로딩을 강제로 호출해 두어야 함?

    hibernate:
      ddl-auto: create
        # ddl-auto: 'option'
        # none : 아무것도 하지 않는다.
        # create : 기존의 테이블이 있다면, 지우고 새로 만듬.
        # create-drop : 테이블을 새로 만들고, 앱이 꺼지기 전에 지운다.
      # update : Entity에서 추가된 필드를 테이블에 반영한다.(테이블 수정)
      # validate : Entity와 테이블의 정합성이 맞는지 검증한다.(안맞으면 오류를 발생 : Application 종료)

    show-sql: true
      # SQL query 출력

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        # hibernate.format_sql: true
          # sql query formatting
        # hibernate.default_batch_fetch_size: 100
          # 설정, in (, , , ,) 의 개수, 100 ~ 1000
        # hibernate.use_sql_comments: true
          #querydsl - jpql parameter

  sql.init.mode: always
    #app실행 시 data.sql 실행

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    key-obtention-iterations: 1000
    password: ${JASYPT_SECRET_KEY}

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ENC(AUfDE+ycjKkyls5vXQy2/tWMkk3YTx5T2Ju7sQAUpWgiqknFtpJ0DQZCOMJUwINPaFgK29KB5AsGKugwg8/d/9I+yKrNXGgKmvJc3ZgL5ttdm/vxS2b6aiX3wwn5xW6aLc45mVyQKkSRE2ZEc+QmQUvnYZ1GAEWEKkbcSqBycxRcrMY8TIGkZ4oAaKf75h7+13lFQmaX5/erFoBP/DbDfRtbP9/uNWRXWoPVDrociR8=)
    username: ENC(QBB/27zo3GmIf9cgWgysvw==)
    password: ENC(m/f4lYdDAfuW9gaTSyxIltrvrKb6nKrp)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none

  sql.init.mode: never

---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: prod1

  datasource:
    url: ENC(AUfDE+ycjKkyls5vXQy2/tWMkk3YTx5T2Ju7sQAUpWgiqknFtpJ0DQZCOMJUwINPaFgK29KB5AsGKugwg8/d/9I+yKrNXGgKmvJc3ZgL5ttdm/vxS2b6aiX3wwn5xW6aLc45mVyQKkSRE2ZEc+QmQUvnYZ1GAEWEKkbcSqBycxRcrMY8TIGkZ4oAaKf75h7+13lFQmaX5/erFoBP/DbDfRtbP9/uNWRXWoPVDrociR8=)
    username: ENC(QBB/27zo3GmIf9cgWgysvw==)
    password: ENC(m/f4lYdDAfuW9gaTSyxIltrvrKb6nKrp)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none

  sql.init.mode: never

---
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: prod2

  datasource:
    url: ENC(AUfDE+ycjKkyls5vXQy2/tWMkk3YTx5T2Ju7sQAUpWgiqknFtpJ0DQZCOMJUwINPaFgK29KB5AsGKugwg8/d/9I+yKrNXGgKmvJc3ZgL5ttdm/vxS2b6aiX3wwn5xW6aLc45mVyQKkSRE2ZEc+QmQUvnYZ1GAEWEKkbcSqBycxRcrMY8TIGkZ4oAaKf75h7+13lFQmaX5/erFoBP/DbDfRtbP9/uNWRXWoPVDrociR8=)
    username: ENC(QBB/27zo3GmIf9cgWgysvw==)
    password: ENC(m/f4lYdDAfuW9gaTSyxIltrvrKb6nKrp)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none

  sql.init.mode: never

